google/XNNPACK

README.md
=> Minor revision in README

WORKSPACE, cmake/DownloadPThreadPool.cmake
See https://github.com/Maratyszcza/pthreadpool/pull/6
=> Update pthreadpoool for support Windows

CMakeLists.txt, src/f32-dwconv-chw/5x5p2-psimd.c
Fix file name in CMakeLists.txt.
Fix missing f16 lib in global-avg-pool test.
Fix psimd function name in 5x5p2-psimd.c.
=> Fix build error on CMake.

WORKSPACE, cmake/DownloadFP16.cmake
Update the cmake download path for fp16.
=> Update FP16 dependency.

include/xnnpack.h, src/runtime.c, src/subgraph/fully-connected.c
Align the behavior to `xnn_create_fully_connected_nc_f32`.
=> Support flags and optional bias for fully_connected node

src/subgraph/deconvolution-2d.c
=> add adjustment height / width

CMakeLists.txt
fmc3-c8.o is not archived in libXNNPACK.a
=> Add fma3-*.c into PROD_FMA3_MICROKERNEL_SRCS

CMakeLists.txt
refer to: https://github.com/google/XNNPACK/runs/6043949096?check_suite_focus=true
=> <fix>: Cmake build error by b5140a4d

src/subgraph/prelu.c
Fix #4692.
@Maratyszcza  PTAL, thanks!
=> Add a data check of slope for prelu operation

CMakeLists.txt, bench/square.cc
=> add f16 square bench

test/x32-packw.cc, tools/generate-packw-test.py
@fbarchard @alankelly Could you help to review this?
=> Fix typo of using wrong group size in packw-test

scripts/generate-xN-transpose.sh
Fix a typo in generate-xN-transpose.sh.
=> Remove redundant colon in generate-xN-transpose.sh

src/subgraph/convolution-2d.c, test/convolution-2d.cc
Reshape Convolution 2d output
```shell
cd XNNPACK
bash script/build-local.sh
cd build/local
make -j9 convolution-2d-test
./convolution-2d-test
```
=> Reshape Conv2d Output

src/subgraph/unpooling-2d.c, test/unpooling-2d.cc
=> Reshape Unpooling Output

CMakeLists.txt, src/subgraph/max-pooling-2d.c, test/BUILD.bazel, test/max-pooling-2d-reshape.cc
Reshape max pool 2d output operator.
Testing:
```shell
cd XNNPACK
bash scripts/build-local.sh
cd build/local
make -j9 max-pooling-2d-reshape-test
./make-pooling-2d-reshape-test
```
=> Reshape MaxPooling2d Output

.gitignore, src/microparams-init.c, src/packing.c, src/xnnpack/microparams-init.h, src/xnnpack/pack.h, test/packing.cc
This is rebased ontop of minor fixes by digant https://github.com/google/XNNPACK/pull/6434
Adds new GIO scalar packing and an additional test for GOI scalar packing
=> [qb4w][packing] gio scalar packing

src/operators/fully-connected-nc.c, src/tensor.c
This pull request fixes a few things that broke in the final stages of rebasing/merging the operator and subgraph-level PRs for QB4W linear.
=> Fix minor issues, cleanup qb4w support

src/f32-qs8-vcvt/gen/f32-qs8-vcvt-hvx-u128.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-hvx-u256.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-hvx-u32.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-hvx-u64.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-hvx-u96.c, src/f32-qs8-vcvt/hvx.c.in, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u128-acc2.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u128-acc3.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u128-acc4.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u128.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u32.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u64-acc2.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u64.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u96-acc2.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u96-acc3.c, src/f32-raddstoreexpminusmax/gen/f32-raddstoreexpminusmax-hvx-rr2-p5-u96.c, src/f32-raddstoreexpminusmax/hvx-rr2-p5.c.in, src/f32-rsum/gen/f32-rsum-hvx-u128-acc2.c, src/f32-rsum/gen/f32-rsum-hvx-u128-acc4.c, src/f32-rsum/gen/f32-rsum-hvx-u32.c, src/f32-rsum/gen/f32-rsum-hvx-u64-acc2.c, src/f32-rsum/gen/f32-rsum-hvx-u96-acc3.c, src/f32-rsum/hvx.c.in, src/qs8-vadd/gen/qs8-vadd-minmax-hvx-u128.c, src/qs8-vadd/gen/qs8-vadd-minmax-hvx-u32.c, src/qs8-vadd/gen/qs8-vadd-minmax-hvx-u64.c, src/qs8-vadd/gen/qs8-vadd-minmax-hvx-u96.c, src/qs8-vadd/hvx.c.in, src/xnnpack/simd/f32-hvx.h
Minor changes in modifying HVX code to new parameter initialization method.
- f32-rsum
- f32-raddstoreexpminus
- qs8-vadd
- f32-qs8
=> Minor changes to adjust new params initialization.

src/f32-qs8-vcvt/gen/f32-qs8-vcvt-rvv-u1v.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-rvv-u2v.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-rvv-u4v.c, src/f32-qs8-vcvt/gen/f32-qs8-vcvt-rvv-u8v.c, src/f32-qs8-vcvt/rvv.c.in, src/f32-qu8-vcvt/gen/f32-qu8-vcvt-rvv-u1v.c, src/f32-qu8-vcvt/gen/f32-qu8-vcvt-rvv-u2v.c, src/f32-qu8-vcvt/gen/f32-qu8-vcvt-rvv-u4v.c, src/f32-qu8-vcvt/gen/f32-qu8-vcvt-rvv-u8v.c
Do zero_point calculation before min/max
=> Fix f32-qs8/qu8 vcvt rvv kernel.

src/operators/fully-connected-nc.c, src/packing.cc, test/fully-connected.cc
There is a bug in stride calculations. We need to scale the stride down by nr. Adding the fix and corresponding test here.
=> Follow Up Patch for Kleidi Integration PR #7003

src/reference/unary-elementwise.cc, src/xnnpack/reference-utils.h, test/binary-elementwise-nd.cc
- Fixed the error where Hexagon build assumes int32_t same as long data type.
=> Fix suggestions for Hexagon to accommodate recent changes

cmake/gen/hvx_microkernels.cmake, gen/hvx_microkernels.bzl, src/configs/transpose-config.c
=> Enable x32-transposec config for HVX

bench/f32-igemm.cc
=> Add f32-igemm benchmark for Hexagon

bench/qp8-f32-qc8w-gemm.cc, cmake/gen/neonsme2_microkernels.cmake, gen/neonsme2_microkernels.bzl, src/configs/gemm-config.c, src/qp8-f32-qc8w-gemm/qp8-f32-qc8w-gemm-minmax-16x64c4-neonsme2.c, src/qp8-f32-qc8w-gemm/qp8-f32-qc8w-gemm-minmax-1x64c4-neonsme2.c, src/xnnpack/gemm.h, test/qp8-f32-qc8w-gemm-minmax.cc, test/qp8-f32-qc8w-gemm-minmax.yaml
- Add support in gemm-config
- Extend unit test
- Extend benchmarks
=> Add SME2 support for qp8_f32_qc8w
