google/XNNPACK

src/runtime.c
`runtime->workspace` is allocated as aligned memory here:
https://github.com/google/XNNPACK/blob/05b98308e59b9abfc8c1206fefc9bebf19d7df4e/src/runtime.c#L332
But it is being deallocated by a non-aligned free operation. This causes an exception when compiled with MSVC and run on windows.
=> Aligned memory incorrectly being deallocated by free()

test/binary-elementwise-operator-tester.h
Some compiler like clang-11 complain about
"use of undeclared identifier 'isfinite'; did you mean 'std::isfinite'?"
TEST: builds and runs
=> Change isfinite() to std::isfinite()

src/init.c
The arguments are flipped, according to https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedcompareexchangepointer. Correcting it so that `init_allocator` is not NULL.
=> Fix allocator initialize issue on Windows

src/init.c
The first operand of `InterlockedCompareExchangePointer` has type `void* volatile* Destination`, thus triggering the warning under clang-cl.
This PR adds explicit type casting to workaround this.
=> Workaround -Wincompatible-pointer-types

src/xnnpack/intrinsics-polyfill.h
When building XNNPACK with MSVC, I got many warnings about missing intrinsics that turned into link errors:
```
f32-dwconv\gen\up32x4-minmax-avx512f.c(153): warning C4013: '_cvtu32_mask16' undefined; assuming extern returning int
...
lld-link: error: undefined symbol: _cvtu32_mask16
```
Adding this patch to correctly define the polyfill for MSVC solved this error.
=> Polyfill missing AVX512 intrinsics on MSVC

src/xnnpack/params.h
As `xnn_hmp_igemm_ukernel` is a struct containing array, it should be initialized as `{{element}}`, otherwise compiler warns about missing braces, as shown in  https://godbolt.org/z/77dsc88T4
=> Fix missing braces around initializer warning

CMakeLists.txt
Enable CMP0091 [1] that allows MSVC runtime library flags to be
selected by an abstraction. It is available in CMake 3.15 and later.
The CMAKE_MSVC_RUNTIME_LIBRARY variable and MSVC_RUNTIME_LIBRARY
target property may be set to select the MSVC runtime library.
For example, supplying
-DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
selects the static MSVC runtime library.
[1]: https://cmake.org/cmake/help/latest/policy/CMP0091.html#policy:CMP0091
=> Select MSVC runtime library for cmake build

src/memory.c, src/mutex.c, src/xnnpack/mutex.h
This issue can be reproduced by building Chromium on Windows with following two flags in args.gn
```
build_with_tflite_lib=true
build_tflite_with_xnnpack=true
```
=> Fix WIN32_LEAN_AND_MEAN redefined warning for Chromium Windows build

src/configs/unary-elementwise-config.c
Was having trouble building and XNNPACK in PyTorch with 
```
set(XNNPACK_ENABLE_ARM_FP16_VECTOR OFF CACHE BOOL "")
```
Specifically, I was seeing the following error with the above flag being set:
```
Undefined symbols for architecture arm64:
"_xnn_f16_qs8_vcvt_ukernel__neonfp16arith_u32", referenced from:
_init_f16_to_qs8_cvt_config in libXNNPACK.a(unary-elementwise-config.c.o)
ld: symbol(s) not found for architecture arm64
```
The change introduced seems to fix this for me.
=> Fix for XNN_ENABLE_ARMFP16_VECTOR Flag

test/f32-vclamp.cc, tools/generate-vunary-test.py
This commit aims to reduce rvv test time for RVV test for `f32-vclamp-test`.
Iterations/Time to run qmin/qmax test increase dramatically when VLEN increases.
This commit adds a scale factor(*10) to step.
The testing time reduces hugely in QEMU.
F32_VCLAMP__RVV_U8V.batch_gt_4v: 784 sec -> 82 sec
Before:
After:
=> Reduce RVV test time for f32-vclamp-test

bench/x16-transpose.cc, bench/x32-transpose.cc, bench/x64-transpose.cc, bench/x8-transpose.cc
Add support for different problem sizes in the xN transpose benchmark. The current benchmarking process addresses problem sizes in the 1xx range, leaving a notable gap before transitioning to a problem size of 1024. This gap impedes a comprehensive evaluation of the correlation between tile size and problem size. This commit incorporates problem sizes HW 128, 256, and 512 to offer a more nuanced exploration of the relationship between tile size and a broader spectrum of problem sizes.
=> Support xN-transpose benchmarking for problem sizes HW128, 256, and 512.

CMakeLists.txt
Tried building the current codebase in my environment now that #5812 is merged, but a couple regressions found their way in:
```
[ 89%] Building CXX object CMakeFiles/add2-reshape-test.dir/test/add2-reshape.cc.o
/home/src/xnnpack/git20231226.9547e12/test/add2-reshape.cc:21:10: fatal error: 'gtest/gtest.h' file not found
21 | #include <gtest/gtest.h>
|          ^~~~~~~~~~~~~~~
1 error generated.
[ 93%] Building CXX object CMakeFiles/abs-reshape-test.dir/test/abs-reshape.cc.o
/home/src/xnnpack/git20231226.9547e12/test/abs-reshape.cc:21:10: fatal error: 'gtest/gtest.h' file not found
21 | #include <gtest/gtest.h>
|          ^~~~~~~~~~~~~~~
1 error generated.
```
This patch gets things working again, but some kind of regression test is needed for this (even if it's just a script grepping …
=> Fix GTest linkage for new tests from commits 576ba7b and 06ae300

src/subgraph/fully-connected.c, test/fully-connected.cc
Changes for dynamic shape support:
* Add output resize support for fully-connected op
* Remove shape_inference methods, no change in the subgraph file yet
* Add support for `XNN_FLAG_TENSORFLOW_RESHAPE_2D`. Not sure if this is used, so haven't added any tests
Other changes:
* Some of the QD tests were not setting the output rank correctly, fix that
* There is a flaky test - not sure if this fix is sufficient but should be in the right direction
=> [Dynamic Shapes] Fully-connected op

src/runtime.c, src/subgraph/scaled-dot-product-attention.c, test/scaled-dot-product-attention.cc
* Add output resize function.
* Add tests for no resize required and resize required similar to
`matches_operator_api`.
* Rationale to add such tests is to make sure shape change works
correctly end-to-end with the intermediate buffers on the
workspace.
* Add a `Resize()` helper function to better manage of input tensors
for user provided shapes and changes in them.
=> [subgraph][sdpa] Add dynamic shape support

include/xnnpack.h, src/subgraph/global-average-pooling.c, src/subgraph/global-sum-pooling.c, src/subgraph/static-mean.c, test/global-average-pooling-1d.cc, test/global-average-pooling-2d.cc, test/global-sum-pooling-1d.cc, test/global-sum-pooling-2d.cc, test/static-mean.cc
KEEP_DIM flag breaks backwards compatibility as global sum pooling, global avg pooling, and static mean now reduce dims by default. 
Instead I recommend switching the flag to xnn_flag_reduce_dim to opt-in to dim reducing so that prior behavior remains the same.
=> XNN_FLAG_KEEP_DIM --> XNN_FLAG_REDUCE_DIM

src/runtime.c
As Title
was having some issues when pthreadpool was set to null here, so made this change. Let me know if this works/passes CI.
@alankelly
=> use runtime threadpool when reshaping ops

src/subgraph/convert.c
I believe dq batch size should be derived from the input shape not output shape in the convert node.
=> [reshape][xnnpack] use input for dq batch size

.bazelrc
Bazel 7.x defaults to expecting MODULE.bazel instead of WORKSPACE unless you specify this flag. XNNPACK should probably migrate to this new scheme, but for now, to avoid the warning (and the creation of a dummy MODULE.bazel file), let's just set this flag to silence it.
(Longer-term, the project should probably migrate to the newer scheme; I looked into doing that but some details of the migration are unclear to me at this time, especially regarding support for the android_sdk/ndk_repository rules.)
=> Add common --enable_bzlmod=false to .bazelrc

src/microparams-init.c, src/packing.c, src/xnnpack/microparams-init.h, src/xnnpack/pack.h, test/packing.cc
Test `packing-test --gtest_filter="PACK_QD8_F32_QB4W_GEMM_GOI_W.*"`
=> [blockwise] GOI packing routine for qb4w

test/f16-vclamp.cc, test/f32-vabs.cc, test/f32-vclamp.cc, test/f32-vhswish.cc, test/f32-vneg.cc, test/f32-vsqr.cc, test/f32-vsqrt.cc, test/qs8-vmul-minmax-fp32.cc, test/qs8-vmulc-minmax-fp32.cc, test/qu8-vmul-minmax-fp32.cc, test/qu8-vmulc-minmax-fp32.cc, test/x32-packw.cc, tools/generate-packw-test.py, tools/generate-raddstoreexpminusmax-test.py, tools/generate-vbinary-test.py, tools/generate-vunary-test.py
Update test scripts of packw, raddstoreexpminusmax, vbinary and vunary. The change will include the test cases for LMUL size 1.
=> Update test scrpit for riscv LMUL size 1

bench/qd8-f16-qb4w-gemm.cc, bench/qd8-f32-qb4w-gemm.cc, scripts/generate-tests.sh, test/gemm-microkernel-tester.cc, test/gemm-microkernel-tester.h, test/qd8-f16-qb4w-gemm-minmax.cc, test/qd8-f32-qb4w-gemm-minmax.cc, tools/generate-gemm-test.py
This PR updates test generation for blockwise (qb4w) kernels in preparation for ISA-specific kernels with kr > 2. Blockwise kernels currently enforce several constraints:
1) Kc is divisible by block size (no partial blocks in a column).
2) Block size is divisible by 2\*kr\*sr (inner loop is 2x unrolled for 2 planes, no partial epilogue).
The majority of the existing gemm tests cover edge cases that are incompatible with the above constraints, so this PR conditionally disables the irrelevant tests for blockwise kernels. Blockwise kernels still have tests for strides, M subtiles, N subtiles, and varying block/k sizes.
Blockwise tests also benefit from linear stepping of nc and kc. Existing test logic always calls NextPrime after incrementing nc and kc values. To allow for linear stepping in …
=> Update test and benchmark generation for blockwise kr>2

src/configs/unary-elementwise-config.c
Fix crash of TensorFlow Lite in function xnn_create_convert_nc_qs8 due to dereferencing null pointer in Android Emulator on armeabi-v7a.
=> Fix crash in Android Emulator with armeabi-v7a.

src/amalgam/gen/wasmrelaxedsimd.c, src/configs/gemm-config.c
This PR is a follow-up work for https://github.com/google/XNNPACK/pull/6505.
| v8/meteor lake                                           | median(Time) / us |
|----------------------------------------------------------|-------------------|
| qs8_qc8w_gemm_2x4c16__wasmusdot/mobilenet_v1/real_time   | 8952              |
| qs8_qc8w_gemm_2x4c16__wasmusdot/mobilenet_v2/real_time   | 7598              |
| qs8_qc8w_gemm_3x4c16__wasmusdot/mobilenet_v1/real_time   | 9629              |
| qs8_qc8w_gemm_3x4c16__wasmusdot/mobilenet_v2/real_time   | 7698              |
| qs8_qc8w_gemm_4x4c16__wasmusdot/mobilenet_v1/real_time   | 9715              |
| qs8_qc8w_gemm_4x4c16__wasmusdot/mobilenet_v2/real_time   | 7994              |
| qs8_qc8w_gemm_2x8c16__wasmusdot/mobilenet_v1/real_time   | 9189 …
=> Enable wasmusdot qs8_qc8w gemm/igemm in gemm-config

cmake/hexagon.toolchain, scripts/build-qurt-v68.sh
- Change build recipes using `-fPIC` to compile object files and link them with `-shared` for the final executables.
- Previous build used object files from HEXAGON_SDK not compiled with -fPIC, so we changed to link the object files compiled with -fPIC.
- Change the simulator command line to use run_main_on_hexagon_sim to reduce loading time.
=> Change build for Hexagon to run kernels on devices

cmake/hexagon.toolchain, scripts/run-on-hexagon-device.sh, scripts/run-on-hexagon-sim.sh
- hexagon.toolchain uses HEXAGON_TOOL_VER=v87, but Hexagon SDK 5.3 doesn't support that version, at least not for run_main_on_hexagon. Downgraded to v86.
- run-main-on-hexagon-sim built incorrect paths based off of HEXAGON_TOOLS_ROOT
- Both of the run-on-hexagon scripts erroneously left `set -x` in place
attn @ejparkqc @dsharlet
=> Minor Fixes to run-on-hexagon scripts + toolchain

src/xnnpack/intrinsics-polyfill.h, src/xnnpack/simd/f32-hvx.h
- Switch from `Q6_Vsf_<opname>_VsfVsf(a,b)` to `Q6_Vsf_equals_Vqf32(Vqf32_<opname>_VsfVsf(a,b))`.
- In simd/f32-hvx.h, we have additional functions named `xnn_<opname>_qf32` having the qf instructions.
- div implementation using Newton-Raphson reciprocal approximation is added. The reciprocal estimate code comes from Halide project.
=> Add qfloat instructions for HVX

CMakeLists.txt
The top-level CMakeLists currently hard-codes python as python3 when invoking generate-build-identifier.py. The python binary may not be named python3 or may not be on the path on all systems. This change uses the CMake-recommended method of using fInd_package(Python) to locate the installed python binary. This works on a wider range of systems and better respects the active python env.
=> Use find_package(Python) to find python at build time

src/pf32-gemm/pf32-gemm-32x32-minmax-neonsme2.c
Currently fails to build when XNN_ENABLE_KLEIDIAI=OFF. Need to wrap these helper methods with the #ifdef kleidiai
=> wrap get_mr and get_nr with #ifdef kleidi

src/qs8-packw/gen/qs8-packw-x8c8-gemm-goi-wasmrelaxedsimd.c, src/qs8-qu8-packw/gen/qs8-qu8-packw-x8c8-gemm-goi-wasmrelaxedsimd.c, src/x8-packw/kr-wasmdot.c.in
Also early load packed_b to avoid an unexpected load rescheduling by compiler and make it revectorizable by V8.
=> Fix c8 packw overread for wasmdot

bench/qs8-dwconv.cc, cmake/gen/rvv_microkernels.cmake, scripts/generate-qs8-dwconv.sh, src/configs/dwconv-config.c, src/qs8-dwconv/gen/qs8-dwconv-25p8vc-minmax-fp32-rvv.c, src/qs8-dwconv/gen/qs8-dwconv-9p8vc-minmax-fp32-rvv.c, src/qs8-dwconv/qs8-dwconv-minmax-unipass-fp32.h, src/qs8-dwconv/unipass-rvv.c.in, src/qs8-qc8w-dwconv/gen/qs8-qc8w-dwconv-25p8vc-minmax-fp32-rvv.c, src/qs8-qc8w-dwconv/gen/qs8-qc8w-dwconv-3p8vc-minmax-fp32-rvv.c, src/qs8-qc8w-dwconv/gen/qs8-qc8w-dwconv-9p8vc-minmax-fp32-rvv.c, src/qs8-qc8w-dwconv/qs8-qc8w-dwconv-minmax-unipass-fp32.h, src/qu8-dwconv/gen/qu8-dwconv-25p8vc-minmax-fp32-rvv.c, src/qu8-dwconv/gen/qu8-dwconv-9p8vc-minmax-fp32-rvv.c, src/qu8-dwconv/qu8-dwconv-minmax-unipass-fp32.h
- Added support for qs8-dwconv and qs8-qc8w-dwconv for RVV
- Generator script can support qu8 but I've left those kernels out given past comments on qu8 being deprecated.
- Tested on qemu and Spacemit K1.
=> [RVV] add qs8-dwconv support for risc-v

MODULE.bazel, WORKSPACE, cmake/DownloadKleidiAI.cmake
Update to release v1.4.0 and use
GitHub mirror repository
=> Update KleidiAI to use GitHub

src/xnnpack/simd/f32-hvx.h, test/unary-ops.h
We needed to use `int32_t` instead of `int` for hexagon build. 
If there is any better fix, please feel free to let me know!
=> Fix hexagon build issue for unary test

bench/subgraph/fp32-transformer.cc, bench/subgraph/qd8-transformer.cc
`std::max` to `std::max<int32_t>` to avoid build error.
=> Explicit type arg in std::max for Hexagon build

src/subgraph.c, test/subgraph/fusion.cc
The zero point should not be coverted to uint8 if the data type is int8.
=> Fix the issue that Pad cannot be fused into conv2d
